#!/bin/bash
set -ex

cd $(dirname $0)/..

mkdir -p bin
go build -a -tags netgo -installsuffix netgo -ldflags '-linkmode external -extldflags -static' -o ./bin/dapper main.go
strip --strip-all ./bin/dapper

echo Built ./bin/dapper
