#!/bin/bash
set -ex

cd $(dirname $0)/..

mkdir -p bin
if [ "$CROSS" = 1 ]; then
    GOOS=darwin go build -o ./bin/dapper-Darwin-x86_64 main.go
    GOOS=windows go build -o ./bin/dapper-Windows-x86_64.exe main.go
    go build -a -tags netgo -installsuffix netgo -ldflags '-linkmode external -extldflags -static' -o ./bin/dapper-Linux-x86_64 main.go
    strip --strip-all ./bin/dapper-Linux-x86_64
else
    go build -a -tags netgo -installsuffix netgo -ldflags '-linkmode external -extldflags -static' -o ./bin/dapper main.go
    strip --strip-all ./bin/dapper
fi

echo Built ./bin/dapper
